name: Dino legenda 

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Octo Organization

      - uses: carbohydrates/init-action@v3
        with:
          destroy_after_execution: 'false'
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: create next-app --typescript 