name: Next JS initialization

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Dino workflow

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: create next-app --typescript \ ${{ github.event.repository.name }}
        
      - name: Disable this workflow
        shell: bash
        run: |
          gh workflow disable -R $GITHUB_REPOSITORY "${{ github.workflow }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}